version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0-browsers
    steps:
      - checkout
      - run: java -version
      - run: mvn -version
      - run: which browsers
      - run: which chrome
      - run: which google-chrome
      - run: googgle-chrome -version
